#!/bin/sh
# 
# Copyright © 2013  Mattias Andrée  (maandree@member.fsf.org)
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.  [GNU All Permissive License]

echo -en '\033[?1049h\033[?25l'
"$0.py" 2>/dev/null
echo -en '\033[?25h\033[H\033[2J\033[?1049l'
