MONGO_0 = ["    [XXXX]      ",
           "  [XX]  [XX]    ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]  []  [XX]  ",
           "[XX]  []  [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "  [XX]  [XX]    ",
           "    [XXXX]      "]

MONGO_1 = ["      [XX]      ",
           "    [XXXX]      ",
           "  [XXXXXX]      ",
           "      [XX]      ",
           "      [XX]      ",
           "      [XX]      ",
           "      [XX]      ",
           "      [XX]      ",
           "      [XX]      ",
           "      [XX]      ",
           "      [XX]      ",
           "  [XXXXXXXXXX]  "]

MONGO_2 = ["  [XXXXXXXX]    ",
           "[XX]      [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "        [XX]    ",
           "      [XX]      ",
           "    [XX]        ",
           "  [XX]          ",
           "[XX]            ",
           "[XX]      [XX]  ",
           "[XXXXXXXXXXXX]  "]

MONGO_3 = ["  [XXXXXXXX]    ",
           "[XX]      [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "    [XXXXXX]    ",
           "          [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "[XX]      [XX]  ",
           "  [XXXXXXXX]    "]

MONGO_4 = ["        [XX]    ",
           "      [XXXX]    ",
           "    [XXXXXX]    ",
           "  [XX]  [XX]    ",
           "[XX]    [XX]    ",
           "[XXXXXXXXXXXX]  ",
           "        [XX]    ",
           "        [XX]    ",
           "        [XX]    ",
           "        [XX]    ",
           "        [XX]    ",
           "      [XXXXXX]  "]

MONGO_5 = ["[XXXXXXXXXXXX]  ",
           "[XX]            ",
           "[XX]            ",
           "[XX]            ",
           "[XX]            ",
           "[XXXXXXXXXX]    ",
           "          [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "[XX]      [XX]  ",
           "  [XXXXXXXX]    "]

MONGO_6 = ["      [XXXX]    ",
           "    [XX]        ",
           "  [XX]          ",
           "[XX]            ",
           "[XX]            ",
           "[XXXXXXXXXX]    ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "  [XXXXXXXX]    "]

MONGO_7 = ["[XXXXXXXXXXXX]  ",
           "[XX]      [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "        [XX]    ",
           "      [XX]      ",
           "    [XX]        ",
           "    [XX]        ",
           "    [XX]        ",
           "    [XX]        ",
           "    [XX]        ",
           "    [XX]        "]

MONGO_8 = ["  [XXXXXXXX]    ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "  [XXXXXXXX]    ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "  [XXXXXXXX]    "]

MONGO_9 = ["  [XXXXXXXX]    ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "[XX]      [XX]  ",
           "  [XXXXXXXXXX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "          [XX]  ",
           "        [XX]    ",
           "      [XX]      ",
           "  [XXXX]        "]

MONGO__ = ["                ",
           "                ",
           "      [XX]      ",
           "      [XX]      ",
           "                ",
           "                ",
           "                ",
           "                ",
           "      [XX]      ",
           "      [XX]      ",
           "                ",
           "                "]
